## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
app_df = application_df.drop(columns=['EIN'])
app_df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [ ]:
# Determine the number of unique values in each column
app_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
app_type_counts = app_df['APPLICATION_TYPE'].value_counts()
app_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_type_counts[app_type_counts < 1000].index)
# app_df['App_Type_Bin'] = pd.cut(app_type_counts, bins=[0, cutoff_value, float('inf')], labels=['Low', 'High'])
# application_types_to_replace = app_type_counts[app_type_counts <= cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    app_df['APPLICATION_TYPE'] = app_df['APPLICATION_TYPE'].replace(app,"Other") #count combines into one value for that feature

# Check to make sure binning was successful
app_df['APPLICATION_TYPE'].value_counts()

T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
class_counts = app_df['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts < 1000].index)
# app_df['App_Type_Bin'] = pd.cut(class_counts, bins=[0, cutoff_value, float('inf')], labels=['Low', 'High'])
# classifications_to_replace = class_counts[class_counts <= cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    app_df['CLASSIFICATION'] = app_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
app_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [ ]:
name_counts = application_df['NAME'].value_counts()
name_counts[name_counts > 300]

PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
PTA TEXAS CONGRESS                                  368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC       331
ALPHA PHI SIGMA                                     313
Name: NAME, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of names to be replaced
# use the variable name `classifications_to_replace`
names_to_replace = list(name_counts[name_counts < 300].index)
# app_df['App_Type_Bin'] = pd.cut(name_counts, bins=[0, cutoff_value, float('inf')], labels=['Low', 'High'])
# classifications_to_replace = name_counts[name_counts <= cutoff_value].index.tolist()

# Replace in dataframe
for name in names_to_replace:
    app_df['NAME'] = app_df['NAME'].replace(name,"Other")

# Check to make sure binning was successful
app_df['NAME'].value_counts()

Other                                              29662
PARENT BOOSTER USA INC                              1260
TOPS CLUB INC                                        765
UNITED STATES BOWLING CONGRESS INC                   700
WASHINGTON STATE UNIVERSITY                          492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC      408
PTA TEXAS CONGRESS                                   368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC        331
ALPHA PHI SIGMA                                      313
Name: NAME, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
app_df_numeric = pd.get_dummies(app_df)
app_df_numeric

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_Other,NAME_PARENT BOOSTER USA INC,NAME_PTA TEXAS CONGRESS,NAME_SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC,NAME_TOPS CLUB INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
#refer to 20.2.05
#axis=0 is rows, axis=1 is columns
features = app_df_numeric.drop(columns=['IS_SUCCESSFUL'])
target = app_df_numeric['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=78)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num = len(X_train_scaled[0]) #number of rows


nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=num))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="tanh"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                4000

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 6461 (25.24 KB)
Trainable params: 6461 (25.24 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
nn

In [ ]:
#  Create a callback
import os
from tensorflow.keras.callbacks import ModelCheckpoint
os.makedirs('AlphabetSoupCharity_Optimization/',exist_ok=True)
path = 'AlphabetSoupCharity_Optimization/weight.{epoch}.hdf5'
callback = ModelCheckpoint(filepath=path, save_weights_only=True, period=5)

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100, callbacks=[callback])

Epoch 1/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5417 - accuracy: 0.7311
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5274 - accuracy: 0.7392
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5238 - accuracy: 0.7414
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5222 - accuracy: 0.7429
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5208 - accuracy: 0.7444
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5199 - accuracy: 0.7441
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5190 - accuracy: 0.7442
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5176 - accuracy: 0.7442
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5177 - accuracy: 0.7451
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5168 - accuracy: 0.7462
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5163 - accuracy: 0.7446
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5159 - accuracy: 0.7469
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5154 - accuracy: 0.7478
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5151 - accuracy: 0.7454
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5144 - accuracy: 0.7480
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5145 - accuracy: 0.7469
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5140 - accuracy: 0.7477
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5138 - accuracy: 0.7470
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5136 - accuracy: 0.7483
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5130 - accuracy: 0.7480
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5126 - accuracy: 0.7485
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5127 - accuracy: 0.7487
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5122 - accuracy: 0.7486
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5120 - accuracy: 0.7481
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5117 - accuracy: 0.7483
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5113 - accuracy: 0.7483
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5113 - accuracy: 0.7496
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5111 - accuracy: 0.7490
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5109 - accuracy: 0.7488
Epoch 30/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5107 - accuracy: 0.7493
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5108 - accuracy: 0.7498
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5106 - accuracy: 0.7497
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5102 - accuracy: 0.7494
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5099 - accuracy: 0.7502
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5096 - accuracy: 0.7499
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5096 - accuracy: 0.7497
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5094 - accuracy: 0.7489
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5094 - accuracy: 0.7497
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5092 - accuracy: 0.7504
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5091 - accuracy: 0.7505
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5087 - accuracy: 0.7496
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5085 - accuracy: 0.7510
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5084 - accuracy: 0.7506
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5082 - accuracy: 0.7506
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5083 - accuracy: 0.7512
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5084 - accuracy: 0.7493
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5083 - accuracy: 0.7511
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5078 - accuracy: 0.7516
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5083 - accuracy: 0.7516
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5079 - accuracy: 0.7503
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5078 - accuracy: 0.7515
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5075 - accuracy: 0.7512
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5074 - accuracy: 0.7519
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5073 - accuracy: 0.7519
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5072 - accuracy: 0.7514
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5071 - accuracy: 0.7519
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5071 - accuracy: 0.7516
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5071 - accuracy: 0.7524
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5070 - accuracy: 0.7507
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5066 - accuracy: 0.7515
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5066 - accuracy: 0.7526
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5068 - accuracy: 0.7525
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5069 - accuracy: 0.7513
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5069 - accuracy: 0.7515
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5066 - accuracy: 0.7517
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5066 - accuracy: 0.7519
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5063 - accuracy: 0.7521
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5065 - accuracy: 0.7519
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5063 - accuracy: 0.7517
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5066 - accuracy: 0.7521
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5060 - accuracy: 0.7521
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5064 - accuracy: 0.7527
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5062 - accuracy: 0.7516
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5057 - accuracy: 0.7522
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5058 - accuracy: 0.7528
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5057 - accuracy: 0.7516
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5058 - accuracy: 0.7524
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5056 - accuracy: 0.7528
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5056 - accuracy: 0.7524
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5061 - accuracy: 0.7525
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5059 - accuracy: 0.7524
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5059 - accuracy: 0.7529
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5052 - accuracy: 0.7527
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5061 - accuracy: 0.7503
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5054 - accuracy: 0.7526
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5062 - accuracy: 0.7521
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5061 - accuracy: 0.7523
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5061 - accuracy: 0.7523
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5057 - accuracy: 0.7520
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5057 - accuracy: 0.7522
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5058 - accuracy: 0.7526
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5055 - accuracy: 0.7525
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5055 - accuracy: 0.7514
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5057 - accuracy: 0.7522
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5061 - accuracy: 0.7526
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5054 - accuracy: 0.7519
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5051 - accuracy: 0.7527
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5054 - accuracy: 0.7523
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5054 - accuracy: 0.7534
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5049 - accuracy: 0.7535

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5257 - accuracy: 0.7392 - 693ms/epoch - 3ms/step
Loss: 0.5256829261779785, Accuracy: 0.7392419576644897

In [ ]:
# Export our model to HDF5 file
tf.keras.saving.save_model(nn, 'AlphabetSoupCharity_Optimization.h5')

<ipython-input-44-3f0dc79a700c>:2: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  tf.keras.saving.save_model(nn, 'my_model_2.h5')