## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
app_df = application_df.drop(columns=['EIN', 'NAME'])
app_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [ ]:
# Determine the number of unique values in each column
app_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
app_type_counts = app_df['APPLICATION_TYPE'].value_counts()
app_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = app_type_counts.median()
app_df['App_Type_Bin'] = pd.cut(app_type_counts, bins=[0, cutoff_value, float('inf')], labels=['Low', 'High'])
application_types_to_replace = app_type_counts[app_type_counts <= cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    app_df['APPLICATION_TYPE'] = app_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
app_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
class_counts = app_df['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = class_counts.median()
app_df['App_Type_Bin'] = pd.cut(class_counts, bins=[0, cutoff_value, float('inf')], labels=['Low', 'High'])
classifications_to_replace = class_counts[class_counts <= cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    app_df['CLASSIFICATION'] = app_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
app_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
Other       55
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1278       10
C1238       10
C1235        9
C1237        9
C7210        7
C1720        6
C2400        6
C4100        6
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
app_df_numeric = pd.get_dummies(app_df)
app_df_numeric

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,App_Type_Bin_Low,App_Type_Bin_High
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,1,108590,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,1,142590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,0

In [ ]:
# Split our preprocessed data into our features and target arrays
#refer to 20.2.05
#axis=0 is rows, axis=1 is columns
features = app_df_numeric.drop(columns=['IS_SUCCESSFUL'])
target = app_df_numeric['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=78)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
num = len(X_train_scaled[0]) #number of rows


nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=num))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="tanh"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 80)                6080

 dense_4 (Dense)             (None, 30)                2430

 dense_5 (Dense)             (None, 1)                 31

=================================================================
Total params: 8541 (33.36 KB)
Trainable params: 8541 (33.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
nn

In [ ]:
#  Create a callback
import os
from tensorflow.keras.callbacks import ModelCheckpoint
os.makedirs('AlphabetSoupCharity/',exist_ok=True)
path = 'AlphabetSoupCharity/weight.{epoch}.hdf5'
callback = ModelCheckpoint(filepath=path, save_weights_only=True, period=5)

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100, callbacks=[callback])

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7434
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7431
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7430
Epoch 4/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5298 - accuracy: 0.7428
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7427
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7431
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7437
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7427
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5304 - accuracy: 0.7428
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7433
Epoch 11/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5297 - accuracy: 0.7428
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5300 - accuracy: 0.7435
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7427
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7425
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5304 - accuracy: 0.7432
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7432
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7422
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5302 - accuracy: 0.7427
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7430
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7434
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7436
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7434
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7432
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7425
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.7433
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.7426
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7427
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7436
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7437
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7432
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7438
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5293 - accuracy: 0.7426
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5289 - accuracy: 0.7447
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7438
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7442
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7432
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7435
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7438
Epoch 39/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5286 - accuracy: 0.7437
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7432
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7440
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7437
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7427
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7432
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7426
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7432
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5286 - accuracy: 0.7430
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7432
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7437
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7434
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7431
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7428
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7433
Epoch 54/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5294 - accuracy: 0.7423
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7425
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7429
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7421
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5307 - accuracy: 0.7430
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7425
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7434
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5295 - accuracy: 0.7427
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5295 - accuracy: 0.7442
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7436
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7437
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7434
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7441
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7439
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7427
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5303 - accuracy: 0.7438
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7437
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5290 - accuracy: 0.7435
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7437
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5296 - accuracy: 0.7438
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5299 - accuracy: 0.7430
Epoch 75/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5292 - accuracy: 0.7434
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7437
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7437
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7443
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7429
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7441
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7438
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5283 - accuracy: 0.7439
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5293 - accuracy: 0.7441
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7441
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7441
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7438
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5287 - accuracy: 0.7439
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5283 - accuracy: 0.7449
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5288 - accuracy: 0.7438
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5286 - accuracy: 0.7430
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7438
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5283 - accuracy: 0.7439
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5285 - accuracy: 0.7431
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7444
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7437
Epoch 96/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5283 - accuracy: 0.7432
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5286 - accuracy: 0.7438
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5301 - accuracy: 0.7430
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7434
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5284 - accuracy: 0.7450

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8575/8575 - 0s - loss: 0.5578 - acc: 0.7263
Loss: 0.557812534073699, Accuracy: 0.7262973785400391

In [ ]:
# Export our model to HDF5 file
tf.keras.saving.save_model(nn, 'AlphabetSoupCharity.h5')